### ISSUE TITLE
How to get printer paper width dynamically ?

### ISSUE THREAD

**Issue by harikrishna1213** [krushkamx/nativescript-hprt#1]
How can we get it worked for all Bluetooth printers ? I need to connect and print on 4 inch, 5 inch and 8 inch and x -inch paper. How do i get the paper width dynamically ?

**Comment by harikrishna1213** [comment]
With this SDK I can able to get device name, device mac address but I want to get device width(Paper width)  to print text for device. What is the process to get device width?

**Comment by davorpeic** [comment]
Hi @harikrishna1213 to be honest not sure most of the printers (maybe the expensive ones) can return paper width automatically, from what I saw that many apps are doing is that you choose manually the width. I can also check if SDK is allowing to ask for this kind of information, it is very limited. Will check and let you know.

**Comment by harikrishna1213** [comment]
Thanks for quick response. I will be waiting for your more info on this.

**Comment by davorpeic** [comment]
Ok, I checked the SDK manual for android, and can't see anything that returns paper width

You can check it yourself for all available commands [Android_ESC_SDK Manual.pdf](https://github.com/krushkamx/nativescript-hprt/files/1731616/Android_ESC_SDK.Manual.pdf) and if you find any that could be, let me know and I can try it
