### ISSUE TITLE
doesn't support vue?

### ISSUE THREAD

**Issue by pdipax** [krushkamx/nativescript-hprt#14]
Hi, this plugin doen't work with nativescript-vue.
will there be updates?
Thanks in advance
P

**Comment by davorpeic** [comment]
Ciao, 
not officially, still working with angular version only, but I saw few weeks back a fork that should bring vue support, you could try to see what is happening here https://github.com/ChobitsSP/nativescript-hprt-vue-demo

Yes we are working on updates, should be soon updated to work fine with latest NS 5.3

dp

**Comment by pdipax** [comment]
Great, thanks.
