### ISSUE TITLE
Able To connect to printer not able to print using  Zebra imz320 printer

### ISSUE THREAD

**Issue by shivaraj-profecia** [krushkamx/nativescript-hprt#3]
Hi,
I have created new application in that i need printing option using its Bluetooth feature in both android and ios  app in native-script(typescript) , currently i am using  nativescript-hprt plugin to print simple text using Zebra imz320 printer but i am not able to print anything, its connecting to printer successfully but when i try to print it shows success but nothing is printing .
Any help would be appreciated 

Thank you

**Comment by davorpeic** [comment]
Hi @shivaraj-profecia, sorry for late feedback, I missed your comment. Zebra uses different interface for printing commands and this plugins doesn't send those, that would be he reason for not working.

For Zebra and Nativescript I know there is a plugin from great developer so you can check it out, it supports ios/android. https://plugins.nativescript.rocks/plugin/NativeScript-Print-Zebra
