### ISSUE TITLE
support nativescript version 4.0?

### ISSUE THREAD

**Issue by yclau** [krushkamx/nativescript-hprt#4]
Hi,
Isn't support nativescript version 4.0?

**Comment by davorpeic** [comment]
Hi @yclau, it should work, but it is not tested yet. Have you tried running it?

**Comment by yclau** [comment]
sorry late reply, after I update it show message below:
nativescript-hprt@0.9.7 requires a peer of tns-core-modules@^3.4.0 but none is installed. You must install peer dependencies yourself.

Currently, my device was broken, waiting new printer coming , haven't test isn't can work or not.

**Comment by davorpeic** [comment]
Hi @yclau plugins is working with Nativescript 5, the message you get is just a warning, if you have latest tns-core-modules installed you should be fine. Will be updated soon
